name: Azure Python 3.11
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.11.11
        uses: actions/setup-python@v1
        with:
          python-version: 3.11.11
      - name: Install dependencies
        run: make install
      - name: Lint
        run: make lint
      - name: Test
        run: make test
